### ISSUE TITLE
%i[]記法でシンプルに記述する

### ISSUE THREAD

**Issue by norotime** [shioimm/.engine#1]
https://github.com/shioimm/.engine/blob/60ab53004387ee0d3ac6ec5e26e72697d11daa55/app/controllers/articles_controller.rb#L2

**Comment by norotime** [comment]
https://github.com/shioimm/.engine/blob/60ab53004387ee0d3ac6ec5e26e72697d11daa55/app/controllers/articles_controller.rb#L3
https://github.com/shioimm/.engine/blob/60ab53004387ee0d3ac6ec5e26e72697d11daa55/app/controllers/articles_controller.rb#L4

**Comment by shioimm** [comment]
PR#1にて解決したたためClose
