### ISSUE TITLE
アソシエーションメソッドを使いシンプルに記述する

### ISSUE THREAD

**Issue by norotime** [shioimm/.engine#6]
https://github.com/shioimm/.engine/blob/60ab53004387ee0d3ac6ec5e26e72697d11daa55/app/controllers/user_services_controller.rb#L3

```
current_user.services.find(params[:id]).destroy
```

**Comment by norotime** [comment]
アソシエーションメソッドは、ActiveRecordのメソッドチェインが使えます。

**Comment by norotime** [comment]
ご自分の環境で、一度試しに実行して挙動を確かめてみてくださいーー。

**Comment by shioimm** [comment]
PR#11にて解決のためClose
